# Generated by Django 2.2.1 on 2019-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryy', '0002_auto_20190527_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordd',
            old_name='Language',
            new_name='language',
        ),
        migrations.AddField(
            model_name='wordd',
            name='word',
            field=models.CharField(max_length=201, null=True),
        ),
    ]
