# Generated by Django 2.2.1 on 2020-05-26 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaryy', '0002_remove_dictionary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='userS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
