# Generated by Django 2.2.1 on 2019-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryy', '0003_auto_20190528_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='words',
            field=models.ManyToManyField(to='dictionaryy.WordD'),
        ),
    ]
