# Generated by Django 2.2.1 on 2020-05-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='user',
        ),
    ]
